{{- if and .Values.backend.enabled .Values.backend.debug.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portal-{{ .Release.Name }}-debug-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"  # Disable SSL redirect for debug
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  rules:
  - host: debug.{{ .Values.global.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: portal-{{ .Release.Name }}-backend
            port:
              number: 5005  # Port HTTP du backend
  # Remove the TLS section for debugging
{{- end }}
