{{- if .Values.flyway.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: portal-{{ .Release.Name }}-flyway-sql-init
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-4"
data:
  V1__baseline.sql: |-
{{ .Files.Get "sql-init/V1__baseline.sql" | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: portal-{{ .Release.Name }}-flyway-sql-global
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-4"
data:
  V1.1__global_schema.sql: |-
{{ .Files.Get "sql-global/V1.1__global_schema.sql" | indent 4 }}
  V1.2__global_seed_data.sql: |-
{{ .Files.Get "sql-global/V1.2__global_seed_data.sql" | indent 4 }}
  V1.3__portal_base_url.sql: |-
{{ .Files.Get "sql-global/V1.3__portal_base_url.sql" | indent 4 }}
{{- end }}
