apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portal-{{ .Release.Name }}-ingress
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.certManagerClusterIssuer }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true" # Add SSL redirect annotation
spec:
  ingressClassName: nginx
  rules:
  - host: "{{ .Values.global.domain }}"
    http:
      paths:
      {{- if .Values.frontend.enabled }}
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: portal-{{ .Release.Name }}-frontend
            port:
              number: 80
      {{- end }}
      {{- if .Values.backend.enabled }}
      - path: /api/
        pathType: Prefix
        backend:
          service:
            name: portal-{{ .Release.Name }}-backend
            port:
              number: 80
      {{- end }}

  tls:
    - hosts:
        - "{{ .Values.global.domain }}"
      secretName: {{ .Values.ingress.secretName | default (printf "%s-letsencrypt-platform" .Release.Name) }}
